---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "copy compiled files"
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu/uda_app

#- name: "copy node_modules"
  #become: yes
  #copy:
    #src: ~/backend/node_modules
    #dest: /home/ubuntu/uda_app

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: "start server"
  become: true
  command: pm2 start -f ./main.js
  args:
    chdir: /home/ubuntu/uda_app/dist
  environment:
   ENVIRONMENT: production
   TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
   TYPEORM_MIGRATIONS_DIR: "./migrations"
   TYPEORM_MIGRATIONS: "./migrations/*.js"
   TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
   TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
   TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
   TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
   TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
   TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
